[package]
name = "rr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
log = "0.4.17"
num_cpus = "1.13.1"
clap = { version = "3.2.20", features = ["derive"] }
crossbeam-channel = "0.5.6"